// SPDX-License-Identifier: MIT
#include "core/skillemitter.h"

#include "mcp/tool.h"
#include "mcp/toolregistry.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QStringList>

namespace {

// Walk the registry the same way ToolRegistry::toJson() does so the order
// matches what an MCP client sees from tools/list. QJsonObject's serializer
// already sorts keys alphabetically, so the JSON-Schema blocks are stable.
QStringList renderTools(const ToolRegistry &registry)
{
    const QJsonArray tools = registry.toJson();
    QStringList sections;
    sections.reserve(tools.size());
    for (const QJsonValue &value : tools) {
        const QJsonObject tool = value.toObject();
        const QString name = tool.value(QStringLiteral("name")).toString();
        const QString description = tool.value(QStringLiteral("description")).toString();
        const QJsonObject schema = tool.value(QStringLiteral("inputSchema")).toObject();

        const QByteArray prettySchema = QJsonDocument(schema).toJson(QJsonDocument::Indented).trimmed();

        QString section;
        section += QStringLiteral("### `") + name + QStringLiteral("`\n\n");
        section += description + QStringLiteral("\n\n");
        section += QStringLiteral("**Input schema:**\n\n");
        section += QStringLiteral("```json\n");
        section += QString::fromUtf8(prettySchema) + QStringLiteral("\n");
        section += QStringLiteral("```\n");
        sections.append(section);
    }
    return sections;
}

} // namespace

QString SkillEmitter::render(const ToolRegistry &registry)
{
    const QStringList sections = renderTools(registry);

    QString out;
    out += QStringLiteral("<!-- AUTO-GENERATED by `plasma-mcp-bridge --emit-skill`. Do not edit. -->\n");
    out += QStringLiteral("## Available tools\n\n");
    out += QStringLiteral("This bridge exposes %1 MCP tool(s). Each tool is invoked via the standard `tools/call` method with the arguments described by its JSON Schema.\n\n")
               .arg(sections.size());
    out += sections.join(QStringLiteral("\n"));
    return out;
}
